CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TYPE user_role AS ENUM ('FARMER','FPO','BUYER','ADMIN','LOGISTICS_PARTNER');
CREATE TYPE record_status AS ENUM ('ACTIVE','DRAFT','LOCKED','FULFILLED','CANCELLED');
CREATE TABLE users (id UUID PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role user_role NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE farmer_profiles (user_id UUID PRIMARY KEY REFERENCES users(id), organization_name TEXT, district TEXT, state TEXT NOT NULL, location geography(POINT,4326), fulfillment_rate NUMERIC(5,2) DEFAULT 0, average_rating NUMERIC(3,2) DEFAULT 0);
CREATE TABLE buyer_profiles (user_id UUID PRIMARY KEY REFERENCES users(id), organization_name TEXT, buyer_type TEXT NOT NULL, gstin TEXT, location geography(POINT,4326));
CREATE TABLE crops (id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, category TEXT);
CREATE TABLE produce_listings (id UUID PRIMARY KEY, farmer_id UUID NOT NULL REFERENCES users(id), crop_id UUID REFERENCES crops(id), quantity_kg NUMERIC NOT NULL CHECK(quantity_kg>0), quality_grade TEXT, asking_price NUMERIC NOT NULL, ready_date DATE NOT NULL, pickup_start TIMESTAMPTZ, pickup_end TIMESTAMPTZ, location geography(POINT,4326), status record_status DEFAULT 'ACTIVE');
CREATE TABLE demand_requests (id UUID PRIMARY KEY, buyer_id UUID NOT NULL REFERENCES users(id), crop_id UUID REFERENCES crops(id), quantity_kg NUMERIC NOT NULL CHECK(quantity_kg>0), quality_requirement TEXT, max_price NUMERIC NOT NULL, delivery_date DATE, delivery_window TEXT, location geography(POINT,4326), status record_status DEFAULT 'DRAFT');
CREATE TABLE orders (id UUID PRIMARY KEY, buyer_id UUID REFERENCES users(id), status record_status DEFAULT 'DRAFT', produce_subtotal NUMERIC NOT NULL, logistics_cost NUMERIC NOT NULL DEFAULT 0, platform_fee NUMERIC NOT NULL DEFAULT 0, total NUMERIC NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE order_items (id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id), listing_id UUID REFERENCES produce_listings(id), farmer_id UUID REFERENCES users(id), quantity_kg NUMERIC NOT NULL, unit_price NUMERIC NOT NULL);
CREATE TABLE compliance_checks (id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id), rule_name TEXT NOT NULL, result TEXT NOT NULL, reason TEXT, required_documents JSONB, source_reference TEXT, checked_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE logistics_requests (id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id), partner_name TEXT, vehicle_type TEXT, quoted_cost NUMERIC, eta_minutes INTEGER, status TEXT, route_geometry geography(LINESTRING,4326));
CREATE TABLE tracking_events (id UUID PRIMARY KEY, logistics_request_id UUID REFERENCES logistics_requests(id), status TEXT NOT NULL, occurred_at TIMESTAMPTZ DEFAULT now(), details JSONB);
CREATE TABLE ratings (id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id), author_id UUID REFERENCES users(id), subject_id UUID REFERENCES users(id), score INTEGER CHECK(score BETWEEN 1 AND 5), comment TEXT);
CREATE TABLE notifications (id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), body TEXT NOT NULL, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE audit_logs (id UUID PRIMARY KEY, actor_id UUID REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id UUID, payload JSONB, occurred_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX listings_geo_idx ON produce_listings USING GIST(location);
CREATE INDEX demands_geo_idx ON demand_requests USING GIST(location);
